"""
Django settings for voyant_l10n_hub project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
import logging
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or "changeme-in-local-dev-only"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "0").lower() in {"1", "true", "yes", "on"}

_allowed_hosts = os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").strip()
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(",") if h.strip()]

# Heroku sends requests with a Host like "<app>.herokuapp.com".
# If you forget to set DJANGO_ALLOWED_HOSTS in Heroku config vars, Django will
# return 400 Bad Request for every request when DEBUG=False.
if os.environ.get("DYNO"):
    heroku_app_name = os.environ.get("HEROKU_APP_NAME", "").strip()
    if heroku_app_name:
        heroku_host = f"{heroku_app_name}.herokuapp.com"
        if heroku_host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(heroku_host)
    elif ".herokuapp.com" not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(".herokuapp.com")

    # Some environments (or configs) may not provide HEROKU_APP_NAME; ensure we still
    # allow the current app's hostname if it's passed explicitly.
    heroku_hostname = os.environ.get("HEROKU_HOSTNAME", "").strip()
    if heroku_hostname and heroku_hostname not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(heroku_hostname)

    # Heroku is always behind a proxy.
    USE_X_FORWARDED_HOST = True


def _env_bool(name: str, default: bool = False) -> bool:
    return os.environ.get(name, "1" if default else "0").lower() in {"1", "true", "yes", "on"}


# If you're behind a proxy that terminates TLS (e.g., Heroku), Django needs this
# to correctly detect HTTPS.
if os.environ.get("DYNO") or _env_bool("DJANGO_BEHIND_PROXY", False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


_csrf_trusted = [
    o.strip()
    for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

# On Heroku (and many platforms), CSRF Origin checking can fail unless the
# deployed origin is explicitly trusted.
if os.environ.get("DYNO"):
    heroku_app_name = os.environ.get("HEROKU_APP_NAME", "").strip()
    if heroku_app_name:
        _csrf_trusted.append(f"https://{heroku_app_name}.herokuapp.com")
    _csrf_trusted.append("https://*.herokuapp.com")

CSRF_TRUSTED_ORIGINS = sorted(set(_csrf_trusted))


# Logging: when DEBUG=False, Django returns a plain 400 for SuspiciousOperation
# (e.g. DisallowedHost). These loggers ensure the underlying reason appears in
# Heroku logs so we can fix it quickly.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "django.security": {
            "handlers": ["console"],
            "level": os.environ.get("DJANGO_SECURITY_LOG_LEVEL", "WARNING"),
        },
        "django.security.DisallowedHost": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": os.environ.get("DJANGO_REQUEST_LOG_LEVEL", "WARNING"),
        },
    },
}

# Cookie security: default to secure cookies on Heroku, but keep local HTTP
# workable unless you opt in.
_secure_cookies_default = bool(os.environ.get("DYNO"))
CSRF_COOKIE_SECURE = _env_bool("DJANGO_CSRF_COOKIE_SECURE", _secure_cookies_default)
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = _env_bool("DJANGO_SESSION_COOKIE_SECURE", _secure_cookies_default)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "l10n.apps.L10NConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "l10n.middleware.RateLimitMiddleware",
]

ROOT_URLCONF = "voyant_l10n_hub.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "voyant_l10n_hub.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

RUNNING_TESTS = (
    os.environ.get("PYTEST_CURRENT_TEST") is not None
    or "pytest" in sys.modules
    or "pytest" in (sys.argv[0] if sys.argv else "")
    or "test" in sys.argv
)

if RUNNING_TESTS:
    test_database_url = os.environ.get("DJANGO_TEST_DATABASE_URL", "").strip()
    if test_database_url:
        DATABASES = {
            "default": dj_database_url.parse(
                test_database_url,
                conn_max_age=0,
            )
        }
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": ":memory:",
            }
        }
else:
    DATABASES = {
        "default": dj_database_url.config(
            default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
            conn_max_age=60,
        )
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
}

# During tests (and typically local dev), we don't run collectstatic, so a
# ManifestStaticFilesStorage would fail when templates reference static assets.
if RUNNING_TESTS or DEBUG:
    STORAGES["staticfiles"] = {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    }
else:
    STORAGES["staticfiles"] = {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "l10n_login"
LOGIN_REDIRECT_URL = "l10n_home"
LOGOUT_REDIRECT_URL = "l10n_home"

# ── Translation Pipeline ───────────────────────────────────────────────────
# Engine choices: "nllb" (local, no key), "openai", "ollama"
TRANSLATION_ENGINE = os.environ.get("TRANSLATION_ENGINE", "nllb")

# NLLB-200: local model downloaded to HuggingFace cache on first use.
# Swap to "facebook/nllb-200-1.3B" for higher quality (requires more RAM/VRAM).
NLLB_MODEL_NAME = os.environ.get("NLLB_MODEL_NAME", "facebook/nllb-200-distilled-600M")

# OpenAI (optional) — set OPENAI_API_KEY in .env to enable
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", "gpt-4o-mini")

# Ollama (optional local LLM) — run `ollama serve` and set model name
OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "llama3")

# XLM-R semantic similarity scoring
# Model downloaded to HuggingFace cache on first use (~420 MB).
SIMILARITY_MODEL = os.environ.get(
    "SIMILARITY_MODEL", "paraphrase-multilingual-mpnet-base-v2"
)
# Strings with back-translation similarity below this threshold get a QA flag.
SIMILARITY_THRESHOLD = float(os.environ.get("SIMILARITY_THRESHOLD", "0.75"))

# Maximum strings processed per web-triggered pipeline run (safety cap).
PIPELINE_WEB_LIMIT = int(os.environ.get("PIPELINE_WEB_LIMIT", "30"))
