# Generated by Django 5.2.9 on 2026-01-06 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Locale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.SlugField(max_length=32, unique=True)),
                ("bcp47", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=128)),
                ("script", models.CharField(blank=True, max_length=16, null=True)),
                ("is_rtl", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=True)),
                ("legacy_column", models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StringUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("message_id", models.CharField(max_length=255)),
                ("source_text", models.TextField(blank=True)),
                ("source_updated_on", models.CharField(blank=True, max_length=64)),
                ("source_hash", models.CharField(db_index=True, editable=False, max_length=64)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("location", "message_id"), name="uniq_location_message_id"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("approved_text", models.TextField(blank=True, null=True)),
                ("reviewer_text", models.TextField(blank=True, null=True)),
                ("machine_draft", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("STALE", "Stale"),
                            ("IN_REVIEW", "In review"),
                            ("MACHINE_DRAFT", "Machine draft"),
                            ("REJECTED", "Rejected"),
                            ("FLAGGED", "Flagged"),
                        ],
                        default="IN_REVIEW",
                        max_length=32,
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("IMPORTED", "Imported"),
                            ("HUMAN", "Human"),
                            ("LLM", "LLM"),
                            ("MT", "MT"),
                        ],
                        default="HUMAN",
                        max_length=16,
                    ),
                ),
                ("source_hash_at_last_update", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="l10n.locale"
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "string_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="l10n.stringunit"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("string_unit", "locale"), name="uniq_string_unit_locale"
                    )
                ],
            },
        ),
    ]
