# Generated by Django 5.2.9 on 2026-01-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("l10n", "0002_localeassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="qa_flags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
