# Generated by Django 5.2.12 on 2026-03-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l10n', '0004_translator_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatorapplication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_photos/'),
        ),
    ]
