# Generated by Django 5.2.12 on 2026-03-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("l10n", "0004_translation_pipeline_fields"),
        ("l10n", "0005_translatorapplication_photo"),
    ]

    operations = []
