# Generated by Django 5.2.7 on 2026-03-22 02:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l10n', '0007_translation_role_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['locale', 'status'], name='idx_translation_locale_status'),
        ),
    ]
