# Generated by Django 5.2.7 on 2026-03-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l10n', '0008_translation_idx_translation_locale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatorapplication',
            name='desired_role',
            field=models.CharField(choices=[('REVIEWER', 'Reviewer'), ('TRANSLATOR', 'Translator'), ('APPROVER', 'Approver')], default='REVIEWER', max_length=16),
        ),
    ]
